# Generated by Django 2.1.5 on 2019-02-11 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=250, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('postcode', models.CharField(blank=True, max_length=20, verbose_name='Индекс')),
                ('country', models.CharField(blank=True, max_length=250, verbose_name='Страна')),
                ('region', models.CharField(blank=True, max_length=250, verbose_name='Регион')),
                ('locality', models.CharField(blank=True, max_length=250, verbose_name='Населенный пункт')),
                ('street', models.CharField(blank=True, max_length=250, verbose_name='Улица')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='Номер квартиры')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
