# Generated by Django 2.1.5 on 2019-02-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='address',
            new_name='apartment_nmb',
        ),
        migrations.AddField(
            model_name='profile',
            name='house_nmb',
            field=models.CharField(blank=True, max_length=250, verbose_name='Номер дома'),
        ),
    ]
