# Generated by Django 2.1.5 on 2019-01-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('address', models.ForeignKey(on_delete='models.CASCADE', to='contacts.Address', verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'E-mail',
                'verbose_name_plural': 'E-mail',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефоны',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=250, verbose_name='Пункт')),
            ],
            options={
                'verbose_name': 'Пункт',
                'verbose_name_plural': 'Пункты',
            },
        ),
        migrations.AddField(
            model_name='contacts',
            name='email',
            field=models.ForeignKey(on_delete='models.CASCADE', to='contacts.Email', verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='phone',
            field=models.ForeignKey(on_delete='models.CASCADE', to='contacts.Phone', verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='schedule',
            field=models.ForeignKey(on_delete='models.CASCADE', to='contacts.Schedule', verbose_name='Режим работы'),
        ),
    ]
