# Generated by Django 2.1.5 on 2019-01-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20190120_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='schedule',
        ),
        migrations.AddField(
            model_name='address',
            name='contacts',
            field=models.ForeignKey(default=1, on_delete='models.CASCADE', to='contacts.Contacts', verbose_name='Контакты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='email',
            name='contacts',
            field=models.ForeignKey(default=12, on_delete='models.CASCADE', to='contacts.Contacts', verbose_name='Контакты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phone',
            name='contacts',
            field=models.ForeignKey(default=1, on_delete='models.CASCADE', to='contacts.Contacts', verbose_name='Контакты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='contacts',
            field=models.ForeignKey(default=12, on_delete='models.CASCADE', to='contacts.Contacts', verbose_name='Контакты'),
            preserve_default=False,
        ),
    ]
