# Generated by Django 2.1.5 on 2019-01-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20190120_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=250, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.CharField(max_length=250, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='point',
            field=models.CharField(max_length=250, null=True, verbose_name='Пункт'),
        ),
    ]
