# Generated by Django 2.1.5 on 2019-01-20 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contacts_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Пункт', 'verbose_name_plural': 'Режим работы'},
        ),
        migrations.RemoveField(
            model_name='address',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='email',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='contacts',
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
