# Generated by Django 2.1.5 on 2019-02-07 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20190120_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='contacts.Contact', verbose_name='Контакт'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='email',
            name='contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='contacts.Contact', verbose_name='Контакт'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phone',
            name='contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='contacts.Contact', verbose_name='Контакт'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='contacts.Contact', verbose_name='Контакт'),
            preserve_default=False,
        ),
    ]
