# Generated by Django 2.1.5 on 2019-02-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_auto_20190207_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='name',
            field=models.CharField(default=1, max_length=250, verbose_name='Название социальной сети'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='social_link',
            field=models.URLField(max_length=250, verbose_name='Ссылка'),
        ),
    ]
