# Generated by Django 2.1.7 on 2019-02-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_messenger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='point',
        ),
        migrations.AddField(
            model_name='schedule',
            name='days_point',
            field=models.CharField(max_length=250, null=True, verbose_name='Дни недели'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='time_point',
            field=models.CharField(max_length=250, null=True, verbose_name='Время работы'),
        ),
    ]
