# Generated by Django 2.1.7 on 2019-02-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='phone',
        ),
        migrations.AddField(
            model_name='feedback',
            name='phone_or_email',
            field=models.CharField(default=1, max_length=250, verbose_name='Номер телефона или E-mail'),
            preserve_default=False,
        ),
    ]
