# Generated by Django 2.1.7 on 2019-03-12 10:38

from django.db import migrations, models
import slider.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('button_text', models.CharField(max_length=250, verbose_name='Текст кнопки')),
                ('button_url', models.URLField(max_length=250, verbose_name='Ссылка кнопки')),
                ('image', models.ImageField(upload_to=slider.models.Slide.get_picture_url, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
            },
        ),
    ]
