# Generated by Django 2.1.7 on 2019-03-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='button_url',
            field=models.CharField(max_length=250, verbose_name='Ссылка кнопки'),
        ),
    ]
