# Generated by Django 2.1.7 on 2019-03-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('text', models.CharField(max_length=250, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Инфо блок',
                'verbose_name_plural': 'Инфо блоки',
            },
        ),
    ]
