# Generated by Django 2.1.5 on 2019-01-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190122_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, help_text='Посчитается при сохранении.', max_digits=10, verbose_name='Итоговая цена'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, help_text='Посчитается при сохранении.', max_digits=10, verbose_name='Цена'),
        ),
    ]
