# Generated by Django 2.1.5 on 2019-02-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20190122_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='comment',
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default=1, max_length=250, verbose_name='Страна'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='locality',
            field=models.CharField(default=1, max_length=250, verbose_name='Населенный пункт'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='region',
            field=models.CharField(default=1, max_length=250, verbose_name='Регион'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(default=1, max_length=250, verbose_name='Улица'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=250, verbose_name='Номер квартиры'),
        ),
    ]
