# Generated by Django 2.1.5 on 2019-02-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20190207_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default='', max_length=250, verbose_name='Номер квартиры'),
        ),
    ]
