# Generated by Django 2.1.5 on 2019-02-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20190211_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='apartment_nmb',
        ),
        migrations.AddField(
            model_name='order',
            name='house_nmb',
            field=models.CharField(default=1, max_length=250, verbose_name='Номер дома'),
            preserve_default=False,
        ),
    ]
