# Generated by Django 2.1.5 on 2019-02-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20190211_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(default='Россия', max_length=250, verbose_name='Страна'),
        ),
    ]
