# Generated by Django 2.1.5 on 2019-02-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20190211_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('pickup', 'Самовывоз'), ('courier', 'Доставка курьером')], max_length=250, verbose_name='Способ доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Итоговая стоимость'),
        ),
    ]
