# Generated by Django 2.1.5 on 2019-02-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20190213_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('pickup', 'Самовывоз'), ('courier', 'Доставка курьероawdawdм')], max_length=250, verbose_name='Способ доставки'),
        ),
    ]
