# Generated by Django 2.1.5 on 2019-02-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20190213_1146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('pickup', 'Самовывоз'), ('courier', 'Доставка курьером')], max_length=250, verbose_name='Способ доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('pickup', 'Самовывоз'), ('courier', 'Доставка курьером')], max_length=250, verbose_name='Способ оплаты'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
