# Generated by Django 2.1.5 on 2019-02-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20190213_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('PICKUP', 'Самовывоз'), ('COURIER', 'Доставка курьером')], default=0, max_length=250, verbose_name='Способ доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('CASH', 'Наличный расчёт'), ('CARD', 'Оплата картой')], default=0, max_length=250, verbose_name='Способ оплаты'),
        ),
    ]
