# Generated by Django 2.1.5 on 2019-02-13 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20190211_1551'),
        ('orders', '0016_auto_20190213_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile', verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
