# Generated by Django 2.1.5 on 2019-02-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20190213_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='address',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Адресс'),
        ),
    ]
