# Generated by Django 2.1.5 on 2019-02-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Итоговая стоимость'),
        ),
    ]
