# Generated by Django 2.1.5 on 2019-02-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20190213_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Посчитается при сохранении.', null=True, verbose_name='Стоимость'),
        ),
    ]
