# Generated by Django 2.1.7 on 2019-02-15 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20190215_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Статус доставки',
                'verbose_name_plural': 'Статусы доставки',
            },
        ),
        migrations.CreateModel(
            name='StatusPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Статус оплаты',
                'verbose_name_plural': 'Статусы оплаты',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='status_delivery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.StatusDelivery', verbose_name='Статус доставки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status_payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.StatusPayment', verbose_name='Статус оплаты'),
            preserve_default=False,
        ),
    ]
