# Generated by Django 2.1.7 on 2019-02-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_auto_20190215_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='apartment_nmb',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Номер квартиры'),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(blank=True, default='Россия', max_length=250, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='order',
            name='house_nmb',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='order',
            name='locality',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Населенный пункт'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='postcode',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Индекс'),
        ),
        migrations.AlterField(
            model_name='order',
            name='region',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='order',
            name='street',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Улица'),
        ),
    ]
