# Generated by Django 2.1.7 on 2019-02-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_auto_20190215_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='saved',
            field=models.BooleanField(default=False, verbose_name='Был сохранен'),
        ),
    ]
