# Generated by Django 2.1.7 on 2019-03-22 09:20

import articles.models
import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('text', tinymce.models.HTMLField()),
                ('published', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_date', models.DateField(default=datetime.date.today, verbose_name='Дата создания')),
                ('image', models.ImageField(upload_to=articles.models.Article.get_picture_url, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
