# Generated by Django 2.1.5 on 2019-02-07 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20190207_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='nanufacturer',
            new_name='manufacturer',
        ),
    ]
