# Generated by Django 2.1.5 on 2019-02-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20190207_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_plural',
            field=models.CharField(default=1, max_length=250, verbose_name='Название(мн.число'),
            preserve_default=False,
        ),
    ]
