# Generated by Django 2.1.5 on 2019-02-08 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_category_name_plural'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_plural',
        ),
    ]
