# Generated by Django 2.1.5 on 2019-02-08 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20190208_1817'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='category',
            index_together={('name', 'slug')},
        ),
    ]
