# Generated by Django 2.1.5 on 2019-02-08 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20190208_1834'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='category',
            index_together=set(),
        ),
    ]
