# Generated by Django 2.1.5 on 2019-02-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20190208_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='release_date',
            field=models.PositiveSmallIntegerField(verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', help_text='Заполнится при сохранении', max_length=250, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(default='', max_length=250, unique=True, verbose_name='Slug'),
        ),
    ]
