# Generated by Django 2.1.5 on 2019-02-10 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20190210_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featurevalue',
            options={'verbose_name': 'Значение характеристики', 'verbose_name_plural': 'Значения характеристики'},
        ),
        migrations.RemoveField(
            model_name='feature',
            name='value',
        ),
    ]
