# Generated by Django 2.1.5 on 2019-02-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20190210_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featurevalue',
            options={'ordering': ['feature'], 'verbose_name': 'Значение характеристики', 'verbose_name_plural': 'Значения характеристики'},
        ),
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(blank=True, null=True, to='shop.FeatureValue', verbose_name='Характеристики'),
        ),
    ]
