# Generated by Django 2.1.5 on 2019-02-10 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20190210_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Модель автомобиля', 'verbose_name_plural': 'Модели автомобилей'},
        ),
        migrations.AlterModelOptions(
            name='carbrand',
            options={'verbose_name': 'Марка автомобиля', 'verbose_name_plural': 'Марки автомобилей'},
        ),
        migrations.AlterModelOptions(
            name='featurevalue',
            options={'ordering': ['feature'], 'verbose_name': 'Значение характеристики', 'verbose_name_plural': 'Значения характеристик'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'Производитель товара', 'verbose_name_plural': 'Производители товаров'},
        ),
        migrations.AddField(
            model_name='product',
            name='car_list',
            field=models.TextField(default=124124124124124124, verbose_name='Список автомобилей'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='shop.CarBrand', verbose_name='Марка автомобиля'),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Модель автомобиля'),
        ),
        migrations.AlterField(
            model_name='carbrand',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Марка автомобиля'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Производитель товара'),
        ),
    ]
