# Generated by Django 2.1.5 on 2019-02-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_product_cars'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['brand'], 'verbose_name': 'Модель автомобиля', 'verbose_name_plural': 'Модели автомобилей'},
        ),
        migrations.AddField(
            model_name='product',
            name='purchased',
            field=models.PositiveIntegerField(default=0, verbose_name='Куплено'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cars',
            field=models.ManyToManyField(blank=True, to='shop.Car', verbose_name='Автомобили'),
        ),
    ]
