# Generated by Django 2.1.5 on 2019-02-10 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_auto_20190210_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurevalue',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_values', to='shop.Feature', verbose_name='Характеристика'),
        ),
        migrations.AlterField(
            model_name='featurevalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_values', to='shop.Product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='Посчитается при сохранении', verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_without_sale',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена без скидки'),
        ),
    ]
