# Generated by Django 2.1.5 on 2019-02-13 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_auto_20190210_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='car_list',
            new_name='cars_list',
        ),
    ]
