# Generated by Django 2.1.7 on 2019-02-15 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_auto_20190214_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='published',
            new_name='is_active',
        ),
    ]
