# Generated by Django 2.1.7 on 2019-02-17 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_auto_20190215_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.PositiveSmallIntegerField(verbose_name='Год выпуска')),
            ],
            options={
                'verbose_name': 'Год выпуска',
                'verbose_name_plural': 'Годы выпуска',
                'ordering': ['car'],
            },
        ),
        migrations.RemoveField(
            model_name='car',
            name='release_date',
        ),
        migrations.AddField(
            model_name='carrelease',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='shop.Car', verbose_name='Год выпуска'),
        ),
    ]
