# Generated by Django 2.1.7 on 2019-02-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_auto_20190217_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='release_date',
        ),
        migrations.AddField(
            model_name='car',
            name='release_date',
            field=models.ManyToManyField(blank=True, null=True, related_name='cars', to='shop.CarRelease', verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cars',
            field=models.ManyToManyField(blank=True, null=True, to='shop.Car', verbose_name='Автомобили'),
        ),
    ]
