# Generated by Django 2.1.7 on 2019-02-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_auto_20190217_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cars',
            field=models.ManyToManyField(blank=True, to='shop.Car', verbose_name='Автомобили'),
        ),
    ]
