# Generated by Django 2.1.7 on 2019-02-18 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_auto_20190217_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.PositiveSmallIntegerField(verbose_name='Год выпуска')),
            ],
            options={
                'verbose_name': 'Год выпуска',
                'verbose_name_plural': 'Годы выпуска',
            },
        ),
        migrations.AlterField(
            model_name='car',
            name='release_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='shop.CarRelease', verbose_name='Год выпуска'),
        ),
    ]
