# Generated by Django 2.1.7 on 2019-02-18 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_auto_20190218_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Модель автомобиля')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars_models', to='shop.CarBrand', verbose_name='Марка автомобиля')),
            ],
            options={
                'verbose_name': 'Модель автомобиля',
                'verbose_name_plural': 'Модели автомобиля',
                'ordering': ['brand'],
            },
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['brand'], 'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.RemoveField(
            model_name='car',
            name='name',
        ),
        migrations.AlterField(
            model_name='car',
            name='release_date',
            field=models.PositiveIntegerField(verbose_name='Год выпуска'),
        ),
        migrations.DeleteModel(
            name='CarRelease',
        ),
        migrations.AddField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='shop.CarModel', verbose_name='Модель автомобиля'),
            preserve_default=False,
        ),
    ]
