# Generated by Django 2.1.7 on 2019-02-18 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_auto_20190218_1249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['car_model'], 'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
    ]
