# Generated by Django 2.1.7 on 2019-02-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_auto_20190218_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='slug',
            field=models.CharField(default=123, max_length=250, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
