# Generated by Django 2.1.7 on 2019-02-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_manufacturer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='slug',
            field=models.CharField(max_length=250, unique=True, verbose_name='Slug'),
        ),
    ]
