# Generated by Django 2.1.7 on 2019-03-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_auto_20190219_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cars',
            field=models.ManyToManyField(blank=True, related_name='products', to='shop.Car', verbose_name='Автомобили'),
        ),
    ]
