# Generated by Django 2.1.7 on 2019-02-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_strings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailfromstring',
            options={'verbose_name': 'Откуда отправлять', 'verbose_name_plural': 'Откуда отправлять'},
        ),
        migrations.AddField(
            model_name='mailfromstring',
            name='email_port',
            field=models.PositiveIntegerField(default=587, verbose_name='EMAIL_PORT'),
        ),
        migrations.AddField(
            model_name='mailfromstring',
            name='email_use_tls',
            field=models.BooleanField(default=True, verbose_name='EMAIL_USE_TLS'),
        ),
    ]
