# Generated by Django 2.1.7 on 2019-02-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20190121_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='partner_url',
            field=models.URLField(default=1, max_length=250, verbose_name='Сайт партнера'),
            preserve_default=False,
        ),
        migrations.AlterIndexTogether(
            name='partner',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='partner',
            name='slug',
        ),
    ]
