# Generated by Django 2.1.7 on 2019-02-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_auto_20190215_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='partner_url',
            field=models.URLField(blank=True, max_length=250, verbose_name='Сайт партнера'),
        ),
    ]
