# Generated by Django 2.1.7 on 2019-03-12 13:01

import about_us.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(default=1, upload_to=about_us.models.AboutUs.get_picture_url, verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
