# Generated by Django 2.1.5 on 2019-02-07 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0002_auto_20190120_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callback',
            name='created',
        ),
        migrations.RemoveField(
            model_name='callback',
            name='name',
        ),
        migrations.AddField(
            model_name='callback',
            name='call_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 7, 14, 37, 49, 312295), verbose_name='Время звонка'),
        ),
    ]
