# Generated by Django 2.1.5 on 2019-02-07 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0003_auto_20190207_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='call_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 7, 14, 56, 50, 282077), verbose_name='Время звонка'),
        ),
    ]
