# Generated by Django 2.1.5 on 2019-02-07 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0004_auto_20190207_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='call_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 7, 14, 58, 32, 90514), verbose_name='Время звонка'),
        ),
    ]
