# Generated by Django 2.1.5 on 2019-02-07 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0010_auto_20190207_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='call_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 7, 16, 7, 50, 193111), verbose_name='Время звонка'),
        ),
    ]
