# Generated by Django 2.1.5 on 2019-02-07 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0011_auto_20190207_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='call_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 7, 17, 30, 13, 268425), verbose_name='Время звонка'),
        ),
    ]
