# Generated by Django 2.1.5 on 2019-02-08 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0012_auto_20190207_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='call_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 8, 17, 8, 15, 247875), verbose_name='Время звонка'),
        ),
    ]
