# Generated by Django 2.1.5 on 2019-02-08 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0013_auto_20190208_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='call_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 8, 17, 18, 25, 116503), verbose_name='Время звонка'),
        ),
    ]
