# Generated by Django 2.1.5 on 2019-02-08 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0015_auto_20190208_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='call_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 8, 17, 46, 25, 332311), verbose_name='Время звонка'),
        ),
    ]
