# Generated by Django 2.1.5 on 2019-02-08 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0021_auto_20190208_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='call_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 8, 18, 24, 55, 993759), verbose_name='Время звонка'),
        ),
    ]
