# Generated by Django 2.1.5 on 2019-02-08 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0033_auto_20190208_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='call_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 8, 19, 31, 39, 437698), verbose_name='Время звонка'),
        ),
    ]
