# Generated by Django 2.1.5 on 2019-02-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0039_auto_20190208_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='call_time',
            field=models.DateTimeField(verbose_name='Время звонка'),
        ),
    ]
