# Generated by Django 2.1.7 on 2019-02-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0040_auto_20190208_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='call_time',
            field=models.CharField(max_length=250, verbose_name='Время звонка'),
        ),
    ]
