# Generated by Django 2.1.7 on 2019-03-12 13:20

from django.db import migrations, models
import our_pros.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurPros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250, verbose_name='Текст')),
                ('image', models.ImageField(upload_to=our_pros.models.OurPros.get_picture_url, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Наш плюс',
                'verbose_name_plural': 'Наши плюсы',
            },
        ),
    ]
