# Generated by Django 2.1.5 on 2019-01-21 13:19

import datetime
from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Slug')),
                ('published', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_date', models.DateField(default=datetime.date.today, verbose_name='Дата создания')),
                ('image', models.ImageField(upload_to=news.models.News.get_picture_url, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
