# Generated by Django 2.1.7 on 2019-02-15 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190213_2015'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='news',
            index_together=set(),
        ),
    ]
