# Generated by Django 2.1.7 on 2019-03-22 08:25

from django.db import migrations, models
import landing.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('text', tinymce.models.HTMLField(verbose_name='Текст')),
                ('image', models.ImageField(upload_to=landing.models.AboutUs.get_picture_url, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Бренд')),
                ('brand_url', models.URLField(blank=True, max_length=250, verbose_name='Сайт бренда')),
                ('image', models.ImageField(upload_to=landing.models.Brand.get_picture_url, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='InfoBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('text', models.CharField(max_length=250, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Инфо блок',
                'verbose_name_plural': 'Инфо блоки',
            },
        ),
        migrations.CreateModel(
            name='OurPros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250, verbose_name='Текст')),
                ('image', models.ImageField(upload_to=landing.models.OurPros.get_picture_url, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Наш плюс',
                'verbose_name_plural': 'Наши плюсы',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Партнер')),
                ('partner_url', models.URLField(blank=True, max_length=250, verbose_name='Сайт партнера')),
                ('image', models.ImageField(upload_to=landing.models.Partner.get_picture_url, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('button_text', models.CharField(blank=True, max_length=250, null=True, verbose_name='Текст кнопки')),
                ('button_url', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка кнопки')),
                ('image', models.ImageField(blank=True, null=True, upload_to=landing.models.Slide.get_picture_url, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
            },
        ),
    ]
