# Generated by Django 2.1.7 on 2019-03-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_topmenupoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topmenupoint',
            name='point_url',
            field=models.CharField(max_length=250, verbose_name='Ссылка на страницу'),
        ),
    ]
