# Generated by Django 2.1.7 on 2019-03-22 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20190322_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topmenupoint',
            name='name',
        ),
        migrations.AlterField(
            model_name='topmenupoint',
            name='point_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flatpages.FlatPage', verbose_name='Страница'),
        ),
    ]
