# Generated by Django 2.1.7 on 2019-03-22 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20190322_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topmenupoint',
            old_name='point_url',
            new_name='point',
        ),
    ]
