# Generated by Django 2.1.7 on 2019-03-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_auto_20190322_1154'),
    ]

    def reorder(apps, schema_editor):
        TopMenuPoint = apps.get_model("landing", "TopMenuPoint")
        order = 0
        for item in TopMenuPoint.objects.all():
            order = order + 1
            item.my_order = order
            item.save()

    operations = [
        migrations.AlterModelOptions(
            name='topmenupoint',
            options={'ordering': ['my_order'], 'verbose_name': 'Пункт верхнего меню', 'verbose_name_plural': 'Пункты верхнего меню'},
        ),
        migrations.AddField(
            model_name='topmenupoint',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Сортировка'),
        ),
        migrations.RunPython(reorder),
    ]